version: '3'
services:

  nginx:
    container_name: nginx1
    build: .docker/nginx
    ports:
      - 80:80
    volumes:
      - ./site:/app
    tty: true
    restart: always
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: .docker/php
      dockerfile: Dockerfile
    environment:
      LANG: 'ja_JP.UTF-8'
      TZ: 'Asia/Tokyo'
      LOG_CHANNEL: 'stderr'
      DB_CONNECTION: 'pgsql'
      DB_HOST: 'db'
      DB_PORT: '5432'
      DB_DATABASE: 'laravel_development'
      DB_USERNAME: 'docker'
      DB_PASSWORD: 'docker'
    volumes:
      - ./site:/app
    expose:
      - 9000
    tty: true
    restart: always
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: db
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_USER: 'docker'
      POSTGRES_PASSWORD: 'docker'
      POSTGRES_DB: 'laravel_development'
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    container_name: app_redis
    build:
      context: .docker/redis
      dockerfile: Dockerfile
    volumes:
      - redis:/data
    ports:
      - 6379:6379

volumes:
  db:
  redis:
    driver: local